!function (C) {
  "use strict";
  var o = C.MapData && C.MapData.thach_phong_thung_lung;
  if (o) {
    o.legend = { ".": { ground: "pebble", block: !1 }, g: { ground: "pebble", block: !1 }, f: { ground: "pebble", block: !1 }, h: { ground: "pebble", block: !1 }, d: { ground: "pebble", block: !1 }, e: { ground: "pebble", block: !1 }, p: { ground: "pebble", block: !1 }, q: { ground: "pebble", block: !1 }, s: { ground: "pebble", block: !1 }, l: { ground: "pebble", block: !1 }, v: { ground: "pebble", block: !1 }, j: { ground: "jade_floor", block: !1 }, w: { ground: "water", block: !0, flyBlock: !1 }, C: { ground: "cliff", block: !0, flyBlock: !0 }, R: { ground: "pebble", block: !0, flyBlock: !1, obj: "rock_big" }, r: { ground: "pebble", block: !1, obj: "rock_small" }, K: { ground: "pebble", block: !0, flyBlock: !0, obj: "karst_pillar" }, b: { ground: "pebble", block: !0, flyBlock: !1, obj: "bush" }, n: { ground: "pebble", block: !1, obj: "reed" }, T: { ground: "pebble", block: !0, flyBlock: !0, obj: "oak_tree" }, P: { ground: "pebble", block: !0, flyBlock: !0, obj: "pine_small" }, S: { ground: "pebble", block: !0, flyBlock: !1, obj: "stele" }, W: { ground: "pebble", block: !0, flyBlock: !1, obj: "ruined_wall" }, U: { ground: "pebble", block: !0, flyBlock: !1, obj: "stump" } };
    o.ground = ["CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCsCCC.C", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCssslssC", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC.slpsCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCsslssCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCssp.sCCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCCssssssssCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCsssssssssCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCsssssssssCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCsssssssssCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCslssCCCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCsl.sCCCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCssldpCCCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCssslddpqCCCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCsslddpq.gCCCCCCCC", "CCCCCCCCCCCCCCCCCCCCCsslddK.pg.hCCCCCCCC", "CCCCCCCCCCCCCCCCCCCssldpq..g.dpCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCsldp.rg..dq.CCCCCCCCC", "CCCCCCCCCCCCCCCssslddp.g.K.dqp.CCCCCCCCC", "CCCCCCCCCCCCssslddqp..g..dpq.grCCCCCCCCC", "CCCCCCCCCCsslddqp.r..gf.dq.pn.CCCCCCCCCC", "CCCCCCCCCsldqp..g.rK.gf.dp.g.bCCCCCCCCCC", "CCCCCCCsldqp.g..r..gf.dpq.g..CCCCCCCCCCC", "CCCCCsldqp.rg.K..g.fhdp.q.g.nCCCCCCCCCCC", "CCCCsldqp..g.r..gf.dRpq..g.SCCCCCCCCCCCC", "CCCvvspq.rg..K..g.dpq..g.rCCCCCCCCCCCCCC", "CvsslpqR..g..r.gdpq.g..rCCCCCCCCCCCCCCCC", "CCvslpq.rg..gdpq..g.rCCCCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"];
    o.decorations = [];
    o.enemies = [{ id: "boss_linh_ho_tran_son", type: "linh_ho_tran_son", tx: 30, ty: 8 }, { id: "bach_ho_tuyet_1", type: "bach_ho_tuyet", tx: 27, ty: 8 }, { id: "bach_ho_tuyet_2", type: "bach_ho_tuyet", tx: 33, ty: 8 }, { id: "bach_ho_tuyet_3", type: "bach_ho_tuyet", tx: 30, ty: 10 }];
    o.interactables = [{ id: "tran_cot_da_von", tx: 21, ty: 22, r: 50, title: "Tran Cot Da Voi", text: "May tru da voi bi nuoc ngam khoet rong dung xieu veo giua long\nthung. Qua nghin nam mua gio chung sut me thanh hinh thu quai di,\ntao mot me cung tu nhien giua bai soi xoi mon." }, { id: "doc_dao_bat_quai", tx: 36, ty: 4, r: 46, title: "Doc Dao Len Bat Quai", text: "Bac da do nguoi deo xen lan da tu nhien luon giua hai vach dung.\nTren cao la Bat Quai Thach Phan; con duong cuoi cung len Thanh\nDai Tan. Linh Ho Tran Son tran giu ngay truoc cua." }, { id: "bia_da_ngach_cut", tx: 29, ty: 25, r: 40, title: "Bia Da Co", text: 'Tam bia mon vet nua chu, dung trong ngach da cut. May dong con\ndoc duoc: "... Ho nam khe, canh duong len troi ... ai qua day, xin\nluong suc ma di ..."' }];
    o.decals = !1;
    o.terrace = { mountain: "C", step: 92, rise: 42, maxLevel: 5, southPad: 22, crest: 3, ridgeStep: 84, seed: 11 };
    o.cuaHam = [{ canh: "W", ty0: 27, ty1: 27, kieu: "go", cuoi: "mo", nen: "nui", ray: !0 }];
  }
}(window.PNTT = window.PNTT || {});
