!function () {
  "use strict";
  var n = window.PNTT.PrologueData = {};
  n.CAST = { hero: { id: "hero", name: "Huyền Thiên Tử", realm: "Kết Đan Trung Kỳ", color: "#ffe08a", maxHp: 1e3, maxMp: 100, cfgOver: { outfit: "than_kiem_y", weapon: "luc_tinh_kiem", aura: "qi_ring", realmId: "truc_co_3", linhCan: "kim", hat: "none", accessory: "none", bag: "none" }, cfgOverMale: { hair: "than_kiem_toc" } }, huyet: { id: "huyet", name: "Huyết Ảnh Lão Quỷ", realm: "Kết Đan Hậu Kỳ", color: "#ff6b7a", maxHp: 26e3, floor: .2, rank: "hau", cfg: { gender: "male", hair: "ma_tu_tan_phat", hairColor: "chu", beard: "tien_ong", outfit: "huyet_anh_y", skin: "pale", eyeColor: "huyet_dong", shoes: "ink", weapon: "huyet_kiem", accessory: "none", bag: "none", aura: "qi_ring", hat: "none", realmId: "truc_co_3", linhCan: "hoa" } }, hacsat: { id: "hacsat", name: "Hắc Sát Chân Nhân", realm: "Kết Đan Hậu Kỳ", color: "#b78cff", maxHp: 24e3, floor: .2, rank: "hau", cfg: { gender: "male", hair: "dai_phu_toc", hairColor: "ngan", beard: "dai_phu_rau", outfit: "hac_y", skin: "light", eyeColor: "tu_dong", shoes: "ink", weapon: "quat_phong", accessory: "none", bag: "none", aura: "qi_ring", hat: "none", realmId: "truc_co_3", linhCan: "am" } }, tuyen: { id: "tuyen", name: "Tử Yên Tiên Tử", realm: "Kết Đan Sơ Kỳ", color: "#e08cff", maxHp: 15e3, floor: .2, rank: "so", cfg: { gender: "female", hair: "xich_diem_toc", hairColor: "tu", beard: "none", outfit: "tu_quang_y", skin: "ngoc_cot", eyeColor: "tu_dong", shoes: "ink", weapon: "bich_nguc_ta_dao", accessory: "none", bag: "none", aura: "qi_ring", hat: "none", realmId: "truc_co_3", linhCan: "phong" } }, lam: { id: "lam", name: "Vương Lâm Tử", realm: "Kết Đan Sơ Kỳ", color: "#7fd6ff", maxHp: 15e3, floor: .2, rank: "so", cfg: { gender: "male", hair: "vuong_lam_toc", hairColor: "ngan", beard: "none", outfit: "vuong_lam_y", skin: "light", eyeColor: "bang_dong", shoes: "ink", weapon: "bach_loi_tien", accessory: "none", bag: "none", aura: "qi_ring", hat: "none", realmId: "truc_co_3", linhCan: "loi" }, spear: "hoang_loi_thuong" } };
  n.SLOTS = { hero: [0, .25], huyet: [-.5, -.12], hacsat: [.52, .1], tuyen: [-.22, -.8], lam: [.26, .82] };
  n.SKILLS = [{ id: "loi", key: 1, name: "Thiên Lôi Phù", kind: "talisman", icon: "loi_dong", mp: 14, cd: 3.6, dmg: .09, color: "#c9a6ff", tip: "Phù hoá sét, giáng ba kẻ gần nhất." }, { id: "bang", key: 2, name: "Băng Kiếm Trận", kind: "skill", icon: "thanh_lam_kiem_tru", mp: 16, cd: 5.5, dmg: .07, color: "#8deaff", tip: "Đóng băng kẻ địch trong trận." }, { id: "kim", key: 3, name: "Kim Quang Cự Kiếm", kind: "skill", icon: "kim_quang_cu_kiem", mp: 18, cd: 7, dmg: .14, color: "#ffd24a", tip: "Kiếm vàng giáng xuống một kẻ." }, { id: "van", key: 4, name: "Vạn Kiếm Quy Tông", kind: "skill", icon: "ngu_kiem_sat", mp: 30, cd: 60, dmg: .22, color: "#a8f5ee", tip: "Vạn kiếm hợp một, quét cả bốn kẻ." }];
  n.HINT = { move: { n: 1, title: "Di chuyển", goal: "Bước vào vòng sáng", phim: ["W", "A", "S", "D", "~hoặc kéo cần gạt bên trái"], cham: ["~Kéo cần gạt bên trái"], sub: "" }, attack: { n: 2, title: "Đánh thường", goal: "Chém Vương Lâm Tử", phim: ["Space", "~hoặc bấm nút ⚔"], cham: ["~Chạm nút ⚔"], sub: "" } };
  n.TEXT = { card1: { title: "TIỀN TRUYỆN", sub: "Tuyệt Mệnh Nhai · đêm trăng máu", line: "Ba trăm năm trước…" }, huyet1: "Huyền Thiên Tử, giao Kim Đan ra. Bọn ta chừa cho ngươi toàn thây.", hero1: "Bốn đánh một, còn dám nói toàn thây? Muốn Kim Đan thì bước qua xác ta!", huyet2: "Vương Lâm, thử xem hắn nặng nhẹ thế nào.", lam1: "Để ta!", lam2: "Hắn… mạnh hơn ta tưởng!", huyet3: "Phế vật. Cùng lên!", hac1: "Nếm thử Ma Bạo Ấn của lão phu!", hero2: "Phù chú, để các ngươi biết tay!", hac2: "Phù bảo hạng nhất… nhưng ngươi còn được mấy tấm?", tuyen1: "Đóng băng ta ư? Chặt gãy là xong!", hero3: "Vạn Kiếm Quy Tông — hết sức đây!", tuyen2: "Hắn cạn Linh Lực rồi! Đừng cho hắn thở!", hero4: "Khụ… hai Hậu Kỳ, hai Sơ Kỳ… giá ta còn một hơi Linh Lực…", hero5: "Đạo ta chưa dứt. Kim Đan… đốt!", huyet4: "Đốt Kim Đan cũng chỉ kéo thêm hai cái xác. Kết thúc!", hero6: "Nếu có kiếp sau… ta sẽ đi lại con đường này.", hac3: "Kiếp sau? Kim Đan này, giờ thuộc về ta.", rebirth: ["Thần hồn tiêu tán. Đại đạo ba nghìn, một sớm hoá hư không.", "Luân Hồi Bàn xoay… một tia tàn hồn lọt qua kiếp.", "Rơi xuống một thôn nhỏ dưới chân núi Tản Viên."], mortal: ["Linh căn mờ nhạt. Đan điền trống rỗng. Kiếp này… chỉ là một phàm nhân.", "Nhưng ký ức kiếp trước vẫn còn nguyên."], end: { title: "KIẾP MỚI", line: "Ta là {ten}. Ta sẽ đi lại từ đầu." }, good: ["Tốt lắm!", "Đúng rồi!", "Chuẩn!"], dodged: "Né được rồi!", hit: "Trúng đòn! Lần sau chạy ra khỏi vòng sáng nhé.", shieldBreak: "Hộ Thể Linh Phù — vỡ!", longBreak: "Giáp Kim Long — vỡ!", lamThuong: "Kim Thương — giáng thế!", lamVu: "Ngũ Lôi — thương vũ!", tuyenTien: "Tiễn Vũ — không chỗ trốn!", tuyenLuan: "Băng Kiếm Luân, tan xương đi!", hacAnh: "Ảnh Kỵ — đuổi hồn!", heroLong: "Kim Long Phù — hộ thể!", huyetLong: "Giáp rồng? Chém nát nó!", heroKimO: "Kim Ô — thiêu sạch!", hacKimO: "Lửa… lửa Kim Ô!", heroTruc: "Lục Tinh Trực Kiếm — khai!", huyetTruc: "Kiếm ảnh lục tinh?! Đừng để hắn lấy lại thế!", heroTran: "Tứ Tượng Thạch Bàn — khai trận!", huyetTran: "Tứ Tượng Trận?! Cùng phá nó!", hacTran: "Vách trận sắp nứt rồi!", tuyenTran: "Phá trận nhãn! Mau!", heroTran2: "Mộc, Hoả, Kim, Thuỷ… giữ cho ta!" };
  n.AUTO = { long: { name: "Kim Long Phù", color: "#ffd24a", shield: 320, secs: 12 }, kimo: { name: "Kim Ô Phù", color: "#ff9a3a", dmg: .09, cd: 24 }, tran: { name: "Tứ Tượng Thạch Bàn", color: "#ffe9a8" }, truc: { name: "Lục Tinh Trực Kiếm", color: "#8dffc0" } };
  n.HERO_FLOOR = .42;
  n.SHIELD = 260;
}();
